alias gst='git status'
alias nvimnvim='nvim ~/.config/nvim/init.vim'
alias logisim='java -jar ~/Downloads/logisim-evolution-3.8.0-all.jar'
alias MARS='java -jar ~/Downloads/Mars4_5.jar'
alias lh='ls -lh'
