alias gst='git status'
alias nvimnvim='nvim ~/.config/nvim/init.vim'
alias logisim='java -jar ~/downloads/logisim-evolution-3.8.0-all.jar'
alias MARS='java -jar ~/downloads/Mars4_5.jar'
alias lh='ls -lh'
alias kitty='~/.local/kitty.app/bin/kitty'
alias nvimkitty='nvim ~/.config/kitty/kitty.conf'
